spring:
  application:
    name: kafka-consumer-demo

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: multi-event-group
      auto-offset-reset: earliest

server:
  port: 8082

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
    istad.co.kafka_consumer_demo: DEBUG